# Generated by Django 5.2.7 on 2025-12-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='Category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
